### ISSUE TITLE
Updated release

### ISSUE THREAD

**Issue by philipcristiano** [clowdhaus/docker-registry#9]
Thanks for taking on the maintenance of this! Would you be able to create a new release as the [OCI manifest](https://github.com/clowdhaus/docker-registry/commit/f76167a17fc5bfc4efdf2b660dc8ac338013fd77) commit is merged in?

**Comment by philipcristiano** [comment]
At the moment I no longer need this, so closing for now

**Comment by bryantbiggs** [comment]
FYI - just in case https://github.com/clowdhaus/docker-registry/releases/tag/v0.7.0
